<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>trip_organizer_api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FirebaseAdmin" Version="3.6.0" />
    <PackageReference Include="Google.Cloud.Firestore" Version="4.4.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="10.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="src/Api/Program.cs" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="src\Api\Features\Auth\" />
    <Folder Include="src\Application\Behaviors\" />
    <Folder Include="src\Application\Common\" />
    <Folder Include="src\Application\Exceptions\" />
    <Folder Include="src\Infrastructure\Persistence\" />
  </ItemGroup>

</Project>
